Repository WildCodeSchool/2022-03-php-orleans-project-rigolou, pull requests merged in 2022-04, with the labels that each got.

#1 initialisation
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#31 S1 us6
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed

#47 S01 us01
  public/assets/css/style.css
  src/View/Components/_navbar.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#48 S1 us02
  .gitignore
  public/assets/css/header.css
  public/assets/css/style.css
  public/assets/images/Family_happy.jpeg
  public/assets/images/Logo.png
  public/assets/images/Title.png
  public/assets/images/bac_balon.jpeg
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed

#55 change --light css variable
  public/assets/css/style.css
Labels: Reviewed, Fix

#54 S01 10
  public/assets/css/cafeteria.css
  public/assets/css/style.css
  public/assets/images/Cafet-1.webp
  src/Controller/CafeteriaController.php
  src/View/Cafeteria/index.html.twig
  src/routes.php
Labels: Conflicts, Reviewed

#56 Fix header overflow on amusement
  public/assets/css/header.css
  public/assets/css/home.css
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed, Fix

#57 changer href for cafeteria in navbar
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed, Fix

#59 S1
  .gitignore
  config/config.php
  database.sql
  public/assets/css/cafeteria.css
  public/assets/css/home.css
  public/assets/css/style.css
  public/assets/images/1200x900_placeholder.png
  public/assets/images/Cafet-1.webp
  public/assets/images/Family_happy.jpeg
  public/assets/images/Logo.png
  public/assets/images/Title.png
  public/assets/images/bac_balon.jpeg
  public/assets/images/bright-squares.png
  public/assets/images/inspiration-geometry.png
  src/Controller/CafeteriaController.php
  src/Controller/HomeController.php
  src/Model/AmusementManager.php
  src/Model/RateManager.php
  src/View/Cafeteria/index.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed

#60 fix H sizes
  public/assets/css/cafeteria.css
  public/assets/css/style.css
Labels: Corrections done, Reviewed, Fix

#61 S1
  public/assets/css/cafeteria.css
  public/assets/css/style.css
Labels: Reviewed

#97 Fix home attraction placeholder
  config/config.php
  database.sql
  public/assets/images/1200x900_placeholder.png
  public/assets/images/attraction_placeholder.jpg
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#98 Fix_Home_Space_Attraction_Title
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#99 Fix_Footer_Card_Navigate_Responsive
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#105 background section same for every pages
  public/assets/css/home.css
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#112 Add some fix for the css (h1, H2, etc ... )
  public/assets/css/style.css
Labels: Reviewed, Fix

#115 new text
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#110 S2 us7 anniversary description
  database.sql
  public/assets/css/anniversary.css
  public/assets/css/style.css
  public/assets/images/anniversary_header.jpg
  src/Controller/AnniversaryController.php
  src/Model/AnniversaryDetailsManager.php
  src/Model/RateManager.php
  src/View/Anniversary/index.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#113 fix color title section
  public/assets/css/style.css
Labels: Reviewed, Fix

#100 Fix_horaires_tarifs_style
  database.sql
  public/assets/css/style.css
  src/Controller/AnniversaryController.php
  src/Controller/HomeController.php
  src/Model/RateManager.php
  src/View/Home/index.html.twig
Labels: Corrections done, Conflicts, Reviewed, Fix

#101 S2 us9 footer
  src/View/Components/_footer.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Conflicts, Reviewed

#116 Dev to main
  config/config.php
  database.sql
  public/assets/css/anniversary.css
  public/assets/css/home.css
  public/assets/css/style.css
  public/assets/images/1200x900_placeholder.png
  public/assets/images/anniversary_header.jpg
  public/assets/images/attraction_placeholder.jpg
  src/Controller/AnniversaryController.php
  src/Controller/HomeController.php
  src/Model/AnniversaryDetailsManager.php
  src/Model/RateManager.php
  src/View/Anniversary/index.html.twig
  src/View/Components/_footer.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed

#103 S2 us33 contact
  composer.json
  composer.lock
  config/config.php
  config/db.php.dist
  src/Controller/ContactController.php
  src/View/Contact/index.html.twig
  src/View/Contact/mail.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#108 S02 us08 cafet
  database.sql
  public/assets/css/cafeteria.css
  public/assets/images/Cafeteria-min.jpg
  public/assets/images/coffee.png
  public/assets/images/patatoes.png
  src/Controller/CafeteriaController.php
  src/Model/CafeteriaManager.php
  src/View/Cafeteria/index.html.twig
Labels: Corrections done, Conflicts, Reviewed

#111 S02 us13 events
  database.sql
  public/assets/css/events.css
  public/assets/images/events.webp
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Events/_eventCards.html.twig
  src/View/Events/index.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#123 Fix database
  database.sql
Labels: Corrections done, Conflicts, Reviewed, Fix

#124 Dev to main
  composer.json
  composer.lock
  config/config.php
  config/db.php.dist
  database.sql
  public/assets/css/cafeteria.css
  public/assets/css/events.css
  public/assets/images/Cafeteria-min.jpg
  public/assets/images/coffee.png
  public/assets/images/events.webp
  public/assets/images/patatoes.png
  src/Controller/CafeteriaController.php
  src/Controller/ContactController.php
  src/Controller/EventController.php
  src/Model/CafeteriaManager.php
  src/Model/EventManager.php
  src/View/Anniversary/index.html.twig
  src/View/Cafeteria/index.html.twig
  src/View/Components/_footer.html.twig
  src/View/Contact/index.html.twig
  src/View/Contact/mail.html.twig
  src/View/Events/_eventCards.html.twig
  src/View/Events/index.html.twig
  src/View/Home/index.html.twig
  src/routes.php
Labels: Reviewed

#119 S2 us3 attractions
  config/config.php
  database.sql
  public/assets/css/amusements.css
  public/assets/css/style.css
  public/assets/images/placeholder.jpg
  src/Controller/AmusementController.php
  src/View/Amusements/index.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed
