Repository WildCodeSchool/2022-03-php-orleans-project-rigolou, pull requests merged in 2022-05, with the labels that each got.

#117 S02 us10 reservation form
  database.sql
  public/assets/css/anniversary.css
  public/assets/images/anniversary_image.jpg
  src/Controller/AnniversaryController.php
  src/Model/AnniversaryManager.php
  src/View/Anniversary/index.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#180 Fix footer disappearing when in mobile
  public/assets/css/style.css
Labels: Reviewed, Fix

#181 Fix some spelling mistakes
  src/View/Components/_navbar.html.twig
  src/View/Contact/index.html.twig
  src/View/Events/index.html.twig
Labels: Reviewed, Fix

#188 Fix nav logo responsive and burger placement
  public/assets/images/logo_nav.png
  src/View/Components/_navbar.html.twig
Labels: Reviewed, Fix

#185 change home header padding
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#186 slightly changed background colors
  public/assets/css/style.css
Labels: Reviewed, Fix

#183 S3 us33 admin attraction liste
  src/Controller/AdminAmusementController.php
  src/View/Admin/Amusement/index.html.twig
  src/View/Admin/_list.html.twig
  src/View/adminLayout.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#189 (Anniversaire) add some style on cards
  src/View/Anniversary/index.html.twig
Labels: Corrections done, Conflicts, Reviewed, Fix

#191 us14 eventshow
  src/Controller/AdminEventController.php
  src/View/Admin/Events/index.html.twig
  src/routes.php
Labels: Corrections done, Reviewed

#193 add background in events section
  src/View/Events/index.html.twig
Labels: Reviewed, Fix

#187 (Contact) add image and change success style
  public/assets/images/contact.png
  src/View/Contact/index.html.twig
Labels: Corrections done, Conflicts, Reviewed, Fix

#190 S3 us29 admin attraction add
  .gitignore
  public/uploads/.gitkeep
  src/Controller/AdminAmusementController.php
  src/Model/AmusementManager.php
  src/View/Admin/Amusement/_form.html.twig
  src/View/Admin/Amusement/add.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#197 S3 us35 admin login
  database.sql
  public/index.php
  src/Controller/AdminAmusementController.php
  src/Controller/AdminEventController.php
  src/Controller/LoginController.php
  src/Model/UserManager.php
  src/View/Login/login.html.twig
  src/routes.php
Labels: Reviewed

#204 dev to main
  .gitignore
  config/config.php
  database.sql
  public/assets/css/amusements.css
  public/assets/css/anniversary.css
  public/assets/css/style.css
  public/assets/images/anniversary_image.jpg
  public/assets/images/contact.png
  public/assets/images/logo_nav.png
  public/assets/images/placeholder.jpg
  public/index.php
  public/uploads/.gitkeep
  src/Controller/AdminAmusementController.php
  src/Controller/AdminCafeteriaController.php
  src/Controller/AdminEventController.php
  src/Controller/AmusementController.php
  src/Controller/AnniversaryController.php
  src/Controller/LoginController.php
  src/Model/AmusementManager.php
  src/Model/AnniversaryManager.php
  src/Model/UserManager.php
  src/View/Admin/Amusement/_form.html.twig
  src/View/Admin/Amusement/add.html.twig
  src/View/Admin/Amusement/index.html.twig
  src/View/Admin/Cafeteria/index.html.twig
  src/View/Admin/Events/index.html.twig
  src/View/Admin/_list.html.twig
  src/View/Amusements/index.html.twig
  src/View/Anniversary/index.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Contact/index.html.twig
  src/View/Events/index.html.twig
  src/View/Home/index.html.twig
  src/View/Login/login.html.twig
  src/View/adminLayout.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed

#203 delete events and img
  src/Controller/AdminEventController.php
  src/View/Admin/Events/index.html.twig
  src/View/Admin/_list.html.twig
  src/routes.php
Labels: Corrections done, Reviewed

#205 Fix_Admin_Attraction_Add_Big_File
  src/Controller/AdminAmusementController.php
Labels: Reviewed, Fix

#199 S3_US30_Attraction_Delete
  0
  src/Controller/AdminAmusementController.php
  src/View/Admin/Amusement/index.html.twig
  src/View/Admin/_list.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#206 S3 us38 admin tarifs show
  src/Controller/AdminRateController.php
  src/Model/RateManager.php
  src/View/Admin/Rate/index.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#213 S3 us31 admin attraction edit
  src/Controller/AdminAmusementController.php
  src/Model/AmusementManager.php
  src/View/Admin/Amusement/_form.html.twig
  src/View/Admin/Amusement/edit.html.twig
  src/View/Admin/Amusement/index.html.twig
  src/routes.php
Labels: Reviewed

#214 done fix home admin
  src/Controller/AdminController.php
  src/Controller/LoginController.php
  src/View/Admin/Home/index.html.twig
  src/routes.php
Labels: Reviewed

#215 Fix bdd form anniversary
  src/Controller/AnniversaryController.php
  src/Model/AnniversaryManager.php
  src/View/Anniversary/index.html.twig
  src/routes.php
Labels: Reviewed, Fix

#208 S03 us18 admin reservation show
  database.sql
  src/Controller/AdminAnniversaryController.php
  src/View/Admin/Anniversary/index.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#210 add the add function for events
  database.sql
  src/Controller/AdminEventController.php
  src/Model/EventManager.php
  src/View/Admin/Events/_form.html.twig
  src/View/Admin/Events/add.html.twig
  src/View/Events/_eventCards.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#217 fix title
  src/View/Events/index.html.twig
Labels: Reviewed

#220 Add FIX for the Design of Cafet pages
  src/View/Cafeteria/index.html.twig
Labels: Corrections done, Reviewed

#221 fix style attractions
  src/View/Amusements/index.html.twig
Labels: Reviewed

#211 S03 us27 cafet add
  src/Controller/AdminCafeteriaController.php
  src/Model/CafeteriaManager.php
  src/View/Admin/Cafeteria/_form.html.twig
  src/View/Admin/Cafeteria/add.html.twig
  src/View/Admin/Cafeteria/index.html.twig
  src/View/Item/_form.html.twig
  src/routes.php
Labels: Conflicts, Reviewed

#223 form reponsive
  src/View/Anniversary/index.html.twig
Labels: Reviewed

#229 Add Route + function delete
  src/Controller/AdminCafeteriaController.php
  src/routes.php
Labels: Reviewed

#228 Admin home title position middle screen
  src/View/Admin/Home/index.html.twig
Labels: Reviewed, Fix

#230 add the edit for events
  database.sql
  src/Controller/AdminEventController.php
  src/Model/EventManager.php
  src/View/Admin/Events/_form.html.twig
  src/View/Admin/Events/edit.html.twig
  src/routes.php
Labels: Reviewed

#227 fix contact style
  src/View/Contact/index.html.twig
Labels: Corrections done, Reviewed, Fix

#224 S3 us22 admin tarifs add
  database.sql
  src/Controller/AdminRateController.php
  src/Model/RateManager.php
  src/View/Admin/Rate/_form.html.twig
  src/View/Admin/Rate/add.html.twig
  src/routes.php
Labels: Corrections done, Reviewed

#225 S3 us39 admin anniversary details show
  src/Controller/AdminAnniversaryDetailController.php
  src/Controller/ItemController.php
  src/Model/ItemManager.php
  src/View/Admin/AnniversaryDetail/index.html.twig
  src/View/Item/_form.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#231 correction lien contact
  src/View/Components/_footer.html.twig
Labels: Corrections done, Reviewed

#232 Fix admin nav links
  src/View/Components/_admin_navbar.html.twig
Labels: Reviewed, Fix

#241 Dev to Main
  database.sql
  public/assets/css/style.css
  src/Controller/AdminAnniversaryController.php
  src/Controller/AdminAnniversaryDetailController.php
  src/Controller/AdminCafeteriaController.php
  src/Controller/AdminEventController.php
  src/Controller/AdminRateController.php
  src/Controller/ItemController.php
  src/Model/CafeteriaManager.php
  src/Model/EventManager.php
  src/Model/ItemManager.php
  src/Model/RateManager.php
  src/View/Admin/Anniversary/index.html.twig
  src/View/Admin/AnniversaryDetail/index.html.twig
  src/View/Admin/Cafeteria/_form.html.twig
  src/View/Admin/Cafeteria/add.html.twig
  src/View/Admin/Cafeteria/index.html.twig
  src/View/Admin/Events/_form.html.twig
  src/View/Admin/Events/add.html.twig
  src/View/Admin/Events/edit.html.twig
  src/View/Admin/Home/index.html.twig
  src/View/Admin/Rate/_form.html.twig
  src/View/Admin/Rate/add.html.twig
  src/View/Amusements/index.html.twig
  src/View/Anniversary/index.html.twig
  src/View/Cafeteria/index.html.twig
  src/View/Components/_admin_navbar.html.twig
  src/View/Components/_footer.html.twig
  src/View/Contact/index.html.twig
  src/View/Events/_eventCards.html.twig
  src/View/Events/index.html.twig
  src/View/Item/_form.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/adminLayout.html.twig
  src/routes.php
Labels: Reviewed

#239 S3 us21 admin tarifs edit
  src/Controller/AdminRateController.php
  src/Model/RateManager.php
  src/View/Admin/Rate/_form.html.twig
  src/View/Admin/Rate/edit.html.twig
  src/routes.php
Labels: Reviewed

#240 Ajout SVG itinéraire
  src/View/Components/_footer.html.twig
Labels: Reviewed

#257 Fix cafet style card
  src/View/Cafeteria/index.html.twig
Labels: Reviewed

#259 S4 us40 admin formule add
  database.sql
  src/Controller/AdminAnniversaryDetailController.php
  src/Model/AnniversaryDetailsManager.php
  src/View/Admin/AnniversaryDetail/_table.html.twig
  src/View/Admin/AnniversaryDetail/add.html.twig
  src/View/Admin/AnniversaryDetail/index.html.twig
  src/routes.php
Labels: Reviewed

#265 Add img for the contact
  public/assets/images/Cafet-1.webp
  public/assets/images/postal.png
  src/View/Contact/index.html.twig
Labels: Corrections done, Reviewed

#266 Delete the black border in bottom card
  src/View/Home/index.html.twig
Labels: Reviewed

#267 fix events done
  src/View/Events/_eventCards.html.twig
  src/View/Events/index.html.twig
Labels: Reviewed

#268 fix orto connexion
  src/View/Components/_admin_navbar.html.twig
  src/View/Login/login.html.twig
Labels: Reviewed

#269 center all admin title
  src/View/Admin/Amusement/add.html.twig
  src/View/Admin/Amusement/edit.html.twig
  src/View/Admin/Amusement/index.html.twig
  src/View/Admin/Anniversary/index.html.twig
  src/View/Admin/AnniversaryDetail/index.html.twig
  src/View/Admin/Cafeteria/add.html.twig
  src/View/Admin/Cafeteria/index.html.twig
  src/View/Admin/Events/add.html.twig
  src/View/Admin/Events/edit.html.twig
  src/View/Admin/Events/index.html.twig
  src/View/Admin/Rate/add.html.twig
  src/View/Admin/Rate/index.html.twig
Labels: Reviewed

#273 modif bouton deconnection admin
  src/View/Components/_admin_navbar.html.twig
Labels: Corrections done, Conflicts, Reviewed

#233 Add route for Edit , edit.html.twig, edit cafeteria manager and contr…
  src/Controller/AdminCafeteriaController.php
  src/Model/CafeteriaManager.php
  src/View/Admin/Cafeteria/_form.html.twig
  src/View/Admin/Cafeteria/edit.html.twig
  src/routes.php
Labels: Reviewed

#272 fix done
  src/Controller/AdminAnniversaryController.php
  src/View/Admin/Anniversary/index.html.twig
  src/routes.php
Labels: Corrections done, Reviewed, Fix

#274 Change img and fix position center
  public/assets/images/Mail.png
  src/View/Contact/index.html.twig
Labels: Corrections done, Reviewed, Fix

#275 fix card img sizes
  public/assets/css/style.css
  src/View/Events/_eventCards.html.twig
Labels: Reviewed, Fix

#260 S4 us21 admin tarif edit
  src/Controller/AdminRateController.php
  src/Model/RateManager.php
  src/View/Admin/Rate/_form.html.twig
  src/View/Admin/Rate/edit.html.twig
  src/View/Admin/Rate/index.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#264 S4 us41 admin formule delete
  src/Controller/AdminAnniversaryDetailController.php
  src/View/Admin/AnniversaryDetail/index.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#276 change picture
  public/assets/images/anniversary_image.jpg
  public/assets/images/anniversary_image.png
  src/View/Anniversary/index.html.twig
Labels: Corrections done, Reviewed, Fix

#242 S03 us19 details for reservation
  database.sql
  src/Controller/AdminAnniversaryController.php
  src/Model/AnniversaryManager.php
  src/View/Admin/Anniversary/details.html.twig
  src/View/Admin/Anniversary/index.html.twig
  src/routes.php
Labels: Corrections done, Conflicts, Reviewed

#270 add retour buton when possible
  src/View/Admin/Amusement/_form.html.twig
  src/View/Admin/Cafeteria/_form.html.twig
  src/View/Admin/Events/_form.html.twig
  src/View/Admin/Rate/_form.html.twig
Labels: Corrections done, Conflicts, Reviewed, Fix

#277 send mail when resa accepted
  src/Controller/AdminAnniversaryController.php
  src/View/Admin/Anniversary/mail.html.twig
Labels: Corrections done, Reviewed, Fix

#280 function delete for reservation admin
  src/View/Admin/Anniversary/index.html.twig
Labels: Reviewed, Fix

#281 add Background font for cafet card
  src/View/Cafeteria/index.html.twig
Labels: Reviewed, Fix

#286 FIX_CONTACT_SPACE
  src/View/Contact/index.html.twig
Labels: Reviewed, Fix

#283 fix titles
  src/View/Contact/index.html.twig
  src/View/Events/index.html.twig
Labels: Corrections done, Conflicts, Reviewed, Fix

#285 fix_Anniversaire_Title_Responsive
  src/View/Anniversary/index.html.twig
Labels: Reviewed, Fix

#288 svg_footer
  src/View/Components/_footer.html.twig
Labels: Reviewed, Fix

#287 create button back
  src/View/Admin/Anniversary/details.html.twig
Labels: Corrections done, Reviewed, Fix

#289 delete novalidate and change button
  src/View/Anniversary/index.html.twig
Labels: Reviewed, Fix

#290 text center
  src/View/Contact/index.html.twig
Labels: Reviewed, Fix

#291 Fix_Login_Responsive
  src/View/Login/login.html.twig
Labels: Reviewed, Fix

#292 FIX_SVG_TARIF_ACC
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#293 delete :
  src/View/Contact/index.html.twig
Labels: Reviewed, Fix

#294 FIX_CAFET_STYLE
  src/View/Cafeteria/index.html.twig
Labels: Reviewed, Fix

#296 FIX_ANNIV_SVG
  public/assets/images/BL.png
  public/assets/images/BL1.png
  src/View/Anniversary/index.html.twig
Labels: Reviewed, Fix

#295 Fix_Header_Text_Size_Color
  public/assets/css/style.css
  src/View/Anniversary/index.html.twig
  src/View/Cafeteria/index.html.twig
  src/View/Home/index.html.twig
Labels: Corrections done, Conflicts, Reviewed, Fix

#297 fix admin style
  src/View/Admin/AnniversaryDetail/_table.html.twig
  src/View/Admin/AnniversaryDetail/add.html.twig
  src/View/Admin/AnniversaryDetail/edit.html.twig
  src/View/Admin/Cafeteria/edit.html.twig
  src/View/Admin/Events/add.html.twig
  src/View/Admin/Events/edit.html.twig
  src/View/Admin/Rate/edit.html.twig
Labels: Corrections done, Reviewed, Fix

#298 fix title
  src/View/Events/index.html.twig
Labels: Corrections done, Reviewed, Fix

#299 FIX_ADMIN_CAFET
  src/View/Admin/Cafeteria/index.html.twig
Labels: Reviewed, Fix

#300 Fix_Anniversaire_Text_No_center
  src/View/Anniversary/index.html.twig
Labels: Reviewed, Fix

#301 tarif, anniv, cafet, cards style
  src/View/Anniversary/index.html.twig
  src/View/Cafeteria/index.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#302 fix admin style
  src/View/Admin/AnniversaryDetail/add.html.twig
  src/View/Admin/AnniversaryDetail/edit.html.twig
  src/View/Admin/AnniversaryDetail/index.html.twig
  src/View/Admin/Cafeteria/index.html.twig
Labels: Reviewed, Fix

#304 Fixed indentation, closing header, deleted unnecessary cafeteria.css
  public/assets/css/cafeteria.css
  src/View/Cafeteria/index.html.twig
Labels: Reviewed, Fix

#305 fix style for details reservation admin
  src/View/Admin/Anniversary/details.html.twig
Labels: Reviewed, Fix

#306 fix button reserver
  src/View/Anniversary/index.html.twig
Labels: Reviewed, Fix

#323 center svg on cards
  src/View/Events/_eventCards.html.twig
Labels: Reviewed, Fix

#326 orthographe de journée
  src/View/Anniversary/index.html.twig
Labels: Reviewed, Fix

#325 Fix w3c on home and footer
  src/View/Components/_footer.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#328 FIX_IMG_CONTACT
  src/View/Contact/index.html.twig
Labels: Reviewed, Fix

#329 Fix edit tarif not showing infos
  src/View/Admin/Rate/_form.html.twig
Labels: Reviewed, Fix

#330 orthographe jours fériés
  database.sql
  src/View/Home/index.html.twig
Labels: Reviewed

#333 not possible to send if the date is exceeded
  src/Controller/AnniversaryController.php
Labels: Reviewed, Fix

#334 change favicon
  public/assets/images/contact.png
  public/assets/images/favicon.png
Labels: Reviewed, Fix

#335 fix home when no amusement in DB
  src/Controller/HomeController.php
Labels: Reviewed, Fix

#336 fix Admin formule when you have no anniversary rate
  src/Controller/AdminAnniversaryDetailController.php
  src/View/Admin/AnniversaryDetail/add.html.twig
  src/View/Admin/AnniversaryDetail/index.html.twig
Labels: Reviewed, Fix

#337 Add a link in admin navbar to go back on user side
  src/View/Components/_admin_navbar.html.twig
Labels: Reviewed, Fix

#338 Fix logo header size
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#342 fix done attractions
  src/View/Admin/Events/_form.html.twig
  src/View/Amusements/index.html.twig
Labels: Corrections done, Reviewed, Fix

#339 En savoir plus button not touching borders on small screens
  src/View/Home/index.html.twig
Labels: Reviewed, Fix

#340 fix placement of the confirmations messages
  src/View/Admin/Amusement/index.html.twig
  src/View/Admin/AnniversaryDetail/index.html.twig
Labels: Corrections done, Conflicts, Reviewed, Fix

#343 Fixed spacing on form contact
  src/View/Contact/index.html.twig
Labels: Reviewed

#341 fix title and event name
  src/View/Events/_eventCards.html.twig
Labels: Reviewed

#344 removed vertical scroll on admin home
  public/assets/css/style.css
  src/View/Admin/Home/index.html.twig
Labels: Reviewed, Fix

#346 nl2br fix for attractions
  src/View/Amusements/index.html.twig
Labels: Reviewed, Fix

#347 FIX_CAFET_RESPONSIVE_CARD
  src/View/Cafeteria/index.html.twig
Labels: Reviewed, Fix

#349 Fix event message
  src/Controller/AdminEventController.php
  src/View/Admin/Events/_form.html.twig
  src/View/Admin/Events/index.html.twig
  src/routes.php
Labels: Reviewed, Fix

#350 FIX_CAFET_PRODUCTS
  database.sql
  src/Controller/AdminCafeteriaController.php
Labels: Reviewed, Fix

#353 removed obsolete attributes on iframe
  src/View/Components/_footer.html.twig
Labels: Reviewed, Fix

#352 changed background alternate color
  public/assets/css/style.css
Labels: Reviewed, Fix

#354 fixed double title on anniversay detail admin
  src/View/Admin/AnniversaryDetail/index.html.twig
Labels: Reviewed, Fix

#355 change text color on reservation admin
  src/View/Admin/Anniversary/index.html.twig
Labels: Reviewed, Fix

#356 Fix_Admin_Cafet_Add_Edit_Button
  src/View/Admin/Cafeteria/_form.html.twig
  src/View/Admin/Cafeteria/add.html.twig
  src/View/Admin/Cafeteria/edit.html.twig
Labels: Reviewed, Fix

#351 FIX_PRICE_ADMIN_CAFET
  src/View/Admin/Cafeteria/_form.html.twig
Labels: Corrections done, Reviewed, Fix

#357 Dev To Main
  database.sql
  public/assets/css/style.css
  public/assets/images/contact.png
  public/assets/images/favicon.png
  src/Controller/AdminAnniversaryController.php
  src/Controller/AdminAnniversaryDetailController.php
  src/Controller/AdminCafeteriaController.php
  src/Controller/AdminEventController.php
  src/Controller/AnniversaryController.php
  src/Controller/HomeController.php
  src/View/Admin/Amusement/index.html.twig
  src/View/Admin/Anniversary/details.html.twig
  src/View/Admin/Anniversary/index.html.twig
  src/View/Admin/AnniversaryDetail/add.html.twig
  src/View/Admin/AnniversaryDetail/index.html.twig
  src/View/Admin/Cafeteria/_form.html.twig
  src/View/Admin/Cafeteria/add.html.twig
  src/View/Admin/Cafeteria/edit.html.twig
  src/View/Admin/Events/_form.html.twig
  src/View/Admin/Events/index.html.twig
  src/View/Admin/Home/index.html.twig
  src/View/Admin/Rate/_form.html.twig
  src/View/Amusements/index.html.twig
  src/View/Anniversary/index.html.twig
  src/View/Cafeteria/index.html.twig
  src/View/Components/_admin_navbar.html.twig
  src/View/Components/_footer.html.twig
  src/View/Contact/index.html.twig
  src/View/Events/_eventCards.html.twig
  src/View/Home/index.html.twig
  src/routes.php
Labels: Reviewed
